import * as ls from './ls.mjs'
import * as me from './me.mjs'
import * as continueEntry from './continue.mjs'
import * as current from './currentTimeEntry.mjs'
import * as workspace from './workspace.mjs'
import * as projects from './projects.mjs'
import * as edit from './edit.mjs'
import * as web from './web.mjs'
import * as startTimeEntry from './startTimeEntry.mjs'
export const commands = [ls, me, continueEntry, current, workspace, projects, edit, web, startTimeEntry]
